#!/bin/bash

FLAGS="-Wall -DONLINE_JUDGE -O2 -fmax-errors=5 -march=native -s"

download_header() {
  local url="$1"
  local output="$2"

  curl -fL --retry 5 --retry-delay 5 "$url" -o "$output"
  if grep -qi "Too Many Requests" "$output"; then
    echo "Downloaded $output contains a rate-limit response" >&2
    return 1
  fi
}

# Download and precompile testlib.h
download_header https://raw.githubusercontent.com/VNOI-Admin/testlib/master/testlib.h /usr/include/testlib.h || \
  cp /judge/testsuite/generator_multifile/testlib.h /usr/include/testlib.h
sed -i '/^#include <cstdio>/a#include <cstdint>' /usr/include/testlib.h
g++ -std=c++17 $FLAGS /usr/include/testlib.h

# Download and precompile testlib_themis_cms.h
download_header https://raw.githubusercontent.com/VNOI-Admin/testlib/master/testlib_themis_cms.h /usr/include/testlib_themis_cms.h
sed -i '/^#include <cstdio>/a#include <cstdint>' /usr/include/testlib_themis_cms.h
mkdir -p /usr/include/testlib_themis_cms.h.gch
g++ -std=c++17 $FLAGS -DTHEMIS /usr/include/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h.gch/themis
g++ -std=c++17 $FLAGS -DCMS    /usr/include/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h.gch/cms
g++ -std=c++17 $FLAGS          /usr/include/testlib_themis_cms.h -o /usr/include/testlib_themis_cms.h.gch/testlib

# Precompile bits/stdc++.h
IFS=$'\n' files=( $(find /usr/include/ -name stdc++.h) );
for item in "${files[@]}"; {
  GCH_DIR="$item".gch
  mkdir -p $GCH_DIR
  eval "g++ -std=c++03 $FLAGS -o $GCH_DIR/cpp03 $item"
  eval "g++ -std=c++11 $FLAGS -o $GCH_DIR/cpp11 $item"
  eval "g++ -std=c++14 $FLAGS -o $GCH_DIR/cpp14 $item"
  eval "g++ -std=c++17 $FLAGS -o $GCH_DIR/cpp17 $item"
  eval "g++ -std=c++20 $FLAGS -o $GCH_DIR/cpp20 $item"
  eval "g++ -std=c++23 $FLAGS -o $GCH_DIR/cpp23 $item"
  eval "g++ -std=gnu++20 -O2 -s -static -o $GCH_DIR/cppicpc $item"
  eval "g++ -std=c++14 -pipe -O2 -s -static -DTHEMIS -o $GCH_DIR/cppthemis $item"
}
